sudo: required
language: c

os: linux
dist: xenial

env:
 - GHCVER=8.2.2
 - GHCVER=8.4.4
 - GHCVER=8.6.5
 - GHCVER=8.10.4

before_install:
 - sudo add-apt-repository -y ppa:hvr/ghc
 - sudo apt-get update
 - sudo apt-get install cabal-install-1.24 ghc-$GHCVER
 - export PATH=/opt/cabal/bin:/opt/ghc/$GHCVER/bin:$PATH

install:
 - cabal-1.24 update
 - cabal-1.24 install --only-dependencies --enable-tests

script:
 - cabal-1.24 configure --enable-tests
 - cabal-1.24 build
 - dist/build/test/test
 - dist/build/test-io/test-io
 - cabal-1.24 haddock
 - cabal-1.24 sdist


